### PR TITLE
Sl360 ad banner

### PR DESCRIPTION
**Pull request by kishore21v**

### CODE REVIEW

**Comment by maartenba** [comment]
@kishore21v Thanks, merged in https://github.com/maartenba/maartenba.github.io/commit/6e101a08eb6d73d6ba22b0d3c69999bbc69efd2c

For future updates, could you create a fresh fork? Right now commit history is a bit overwhelming.

**Comment by kishore21v** [comment]
Sure Maarten!

**Comment by kishore21v** [comment]
Hi Maarten,
I tried to create a fork. But I've already forked your repo. So it won't
allow forking again. I have updated the banner with small changes in
content. Can you pl. check and merge the code?

Thanks!

**Comment by maartenba** [comment]
Just updated the files, deploying right now.

**Comment by kishore21v** [comment]
Thanks Maarten

**Pull request closed without merging**
